[package]
name = "hawkin-on-that-tuah"
version = "0.1.0"
edition = "2024"

[dependencies]
rusty-duplication = "0.6.1"
winapi = { version = "0.3.9", features = ["winuser"] }

[build-dependencies]
embed-resource = "3.0.6"